# fly.toml app configuration file generated for moviepals on 2023-08-21T12:37:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moviepals"
primary_region = "lax"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
