services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  movie-swipe-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - movie-swipe-db-data:/data/db

  db:
    container_name: moviepals-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - moviepals-db-dev:/moviepals
    environment:
      POSTGRES_USER: moviepals
      POSTGRES_PASSWORD: moviepalsdev
      PGDATA: /moviepals

volumes:
  moviepals-db-dev:
  movie-swipe-db-data:
